[tool.poetry]
name = "mediaaio"
version = "0.1.0"
description = ""
authors = ["NightWatcher <hitszzzf@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^1.26.4"
openai-whisper = "^20231117"
gradio = "^4.17.0"
final2x-core = "^2.0.0"
aiofiles = "^23.2.1"
flask = "^3.0.2"
streamlit = "^1.31.0"
requests = "^2.31.0"
streamlit-ext = "^0.1.9"


[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
